security:
    password_hashers:
        App\AdminUser\Entity\AdminUser:
            algorithm: auto
            migrate_from: []
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        admin_user_provider:
            entity:
                class: App\AdminUser\Entity\AdminUser
                property: admin_name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            security: false
        catalog:
            pattern: ^/api/catalog
            stateless: true
            provider: admin_user_provider
            custom_authenticators:
                - App\Bot\Security\BotApiKeyAuthenticator
        api:
            pattern: ^/api
            stateless: true
            provider: admin_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/catalog, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: [ ROLE_ADMIN, ROLE_SUPER_ADMIN ] }
